# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExchangeRate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExchangeRate
  pod 'SwiftLint'
  pod 'R.swift'

  target 'ExchangeRateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExchangeRateUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
